# Generated by Django 4.2.7 on 2025-04-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='apartment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='entrance',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='floor',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='house',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
