# Generated by Django 4.2.7 on 2025-03-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
