# Generated by Django 4.2.7 on 2025-04-19 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_userlocation_apartment_userlocation_entrance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('can_add', 'Доступ добавить'), ('can_update', 'Доступ обновить'), ('can_delete', 'Доступ удалить'), ('can_view', 'Доступ на просмотр')], max_length=255)),
                ('perms', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('is_supervisor', 'Супервайзер'), ('is_manager', 'Менеджер'), ('is_director', 'Директор'), ('is_analytic', 'Аналитик'), ('is_hr', 'HR'), ('is_agent', 'Агент'), ('is_owner', 'Создатель'), ('is_superadmin', 'Super admin')], max_length=255)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('code', models.ManyToManyField(related_name='roles', to='users.permissions')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_perms', to='users.permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='users.userrole'),
        ),
    ]
