# Generated by Django 4.2.7 on 2025-04-20 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlocation_apartment_userlocation_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер в международном формате начинается с +', regex='^(\\+)(\\d{12})$')]),
        ),
    ]
