# Generated by Django 4.2.7 on 2025-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
