# Generated by Django 4.2.7 on 2025-04-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userlocation_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
