# Generated by Django 4.2.7 on 2025-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userlocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
