# Generated by Django 4.2.7 on 2025-04-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userlocation_address_userlocation_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['id']},
        ),
    ]
