# Generated by Django 4.2.7 on 2025-04-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_permissions_alter_user_is_superuser_userrole_and_more'),
        ('users', '0009_alter_userlocation_options'),
    ]

    operations = [
    ]
