# Generated by Django 4.2.7 on 2025-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_usersettings_id_alter_usersettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('is_supervisor', 'Супервайзер'), ('is_manager', 'Менеджер'), ('is_director', 'Директор'), ('is_analytic', 'Аналитик'), ('is_hr', 'HR'), ('is_agent', 'Агент'), ('is_courier', 'Курьер'), ('is_dispatcher', 'Диспетчер'), ('is_operator', 'Оператор'), ('is_waiter', 'Официант'), ('is_super_waiter', 'Старший официант')], max_length=255),
        ),
    ]
