version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: aurora_db
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aurora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./aurora_backup.sql:/docker-entrypoint-initdb.d/backup.sql

  redis:
    image: redis:7
    container_name: aurora_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]


volumes:
  postgres_data:
  redis_data:
