# Generated by Django 4.2.7 on 2025-03-16 07:15

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import menu_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=225, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=menu_app.models.upload_path_menu)),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=menu_app.models.upload_path_promo)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=False)),
                ('telegram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_photo', models.FileField(null=True, upload_to=menu_app.models.upload_path_rest)),
                ('logo', models.FileField(null=True, upload_to=menu_app.models.upload_logo_rest)),
                ('availability_orders', models.BooleanField(default=False)),
                ('orders_chat_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999999999999), django.core.validators.MaxValueValidator(9999999999999)])),
                ('waiter_chat_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999999999999), django.core.validators.MaxValueValidator(9999999999999)])),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
