# Generated by Django 4.2.7 on 2025-03-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='photo',
            new_name='background_photo',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='instagramm',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='telegram',
            new_name='telegram_link',
        ),
    ]
