# Generated by Django 4.2.7 on 2025-03-18 16:51

from django.db import migrations, models
import menu_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='photo',
            new_name='background_photo',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='instagramm',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='telegram',
            new_name='telegram_link',
        ),
        migrations.AddField(
            model_name='menu',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=menu_app.models.upload_path_menu),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
