# Generated by Django 4.2.7 on 2025-03-16 11:23

from django.db import migrations, models
import menu_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_rename_adress_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=menu_app.models.upload_path_menu),
        ),
    ]
