# Generated by Django 4.2.7 on 2025-04-04 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu_app', '0003_menu_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='thumb',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
