# Generated by Django 4.2.7 on 2024-02-29 17:30

from django.db import migrations, models
import menu_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=menu_app.models.upload_path_promo),
        ),
    ]
