# Generated by Django 4.2.7 on 2025-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_restaurant_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='long',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
