# Generated by Django 4.2.7 on 2025-05-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0007_restaurant_lat_restaurant_long'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
