# Generated by Django 4.2.7 on 2024-06-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0007_alter_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='info',
            new_name='description',
        ),
    ]
