# Generated by Django 4.2.7 on 2024-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_rename_info_promo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='availability_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orders_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiter_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
