# Generated by Django 4.2.7 on 2025-06-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_variant_delete_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='size',
            new_name='name',
        ),
    ]
