# Generated by Django 4.2.7 on 2024-06-26 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_alter_restaurant_orders_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='orders_chat_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-100000000000000), django.core.validators.MaxValueValidator(100000000000000)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='waiter_chat_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-100000000000000), django.core.validators.MaxValueValidator(100000000000000)]),
        ),
    ]
