# Generated by Django 4.2.7 on 2025-06-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0011_alter_category_is_active_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='menu_app.restaurant'),
        ),
    ]
