# Generated by Django 4.2.7 on 2025-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0012_alter_category_is_active_alter_schedule_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=100),
        ),
    ]
