# Generated by Django 4.2.7 on 2024-12-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0012_alter_restaurant_orders_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
