# Generated by Django 4.2.7 on 2025-06-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0013_alter_category_is_active_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
