# Generated by Django 4.2.7 on 2025-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0015_alter_category_is_active_deliveryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrule',
            name='price_per_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_km', 'Цена за километр'), ('percent', 'Процент от суммы заказа')], max_length=10),
        ),
    ]
