# Generated by Django 4.2.7 on 2025-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0016_deliveryrule_price_per_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
