# Generated by Django 4.2.7 on 2025-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0017_deliveryrule_description_deliveryrule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
