# Generated by Django 4.2.7 on 2025-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0018_alter_deliveryrule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrule',
            name='reverse_calculate',
            field=models.BooleanField(default=False),
        ),
    ]
