# Generated by Django 4.2.7 on 2025-08-28 23:06

from django.db import migrations, models
import menu_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0020_restaurantdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='native_background_photo',
            field=models.ImageField(blank=True, null=True, upload_to=menu_app.models.upload_path_rest),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='native_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=menu_app.models.upload_path_rest),
        ),
    ]
