# Generated by Django 4.2.7 on 2025-08-29 00:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0021_restaurant_native_background_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
